name: 🚀 Deploy to Hostinger
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout Code
        uses: actions/checkout@v4

      - name: 🚀 Sync Files via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: 157.173.214.226
          REMOTE_USER: u560553433
          REMOTE_PORT: 65002
          ARGS: "-rlgoDzvc -e 'ssh -p 65002 -o StrictHostKeyChecking=no' --delete"
          SOURCE: "/"
          TARGET: "/domains/houseofexhibitions.com/public_html/"
          EXCLUDE: "/.git/, /.github/, /node_modules/"
